"""
Calculate correlation between ROA/EBIT-PPE and forward return by period
For each period, calculate correlation across all stocks
Reads data from metrics.json (generated by metrics.py)
"""
import json
import numpy as np
from scipy.stats import pearsonr, spearmanr, rankdata
from typing import List, Tuple
import matplotlib.pyplot as plt

def load_data(filename: str = "metrics.json") -> List[dict]:
    """
    Load stock data from JSON file (metrics.json)
    
    Args:
        filename: Path to JSON file (default: metrics.json)
        
    Returns:
        List of stock data dictionaries
    """
    try:
        with open(filename, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: {filename} not found")
        return []
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON in {filename}")
        return []

def extract_data_by_period(data: List[dict], metric_keys: List[str] = None) -> dict:
    """
    Extract metrics and forward return data grouped by period
    For each period, collect all stocks' metric values and forward_return values
    
    Args:
        data: List of stock data dictionaries
        metric_keys: List of metric keys to extract (if None, auto-detect from data)
        
    Returns:
        Dictionary mapping period -> {metric_key: [values], 'forward_return_' + metric_key: [values]}
    """
    period_data = {}
    
    # Auto-detect metric keys if not provided
    if metric_keys is None:
        metric_keys = []
        for stock in data:
            for entry in stock.get("data", []):
                # Find all numeric metrics (excluding period, price, dividends, total_return, forward_return)
                excluded_keys = {'period', 'price', 'dividends', 'total_return', 'forward_return'}
                for key, value in entry.items():
                    if key not in excluded_keys and value is not None and isinstance(value, (int, float)):
                        if key not in metric_keys:
                            metric_keys.append(key)
                break  # Only need to check one entry
    
    for stock in data:
        symbol = stock.get("symbol", "Unknown")
        for entry in stock.get("data", []):
            period = entry.get("period")
            forward_return = entry.get("forward_return")
            
            # Skip invalid periods (like 0 or None)
            if period is None or period == 0:
                continue
            
            # Initialize period if not exists
            if period not in period_data:
                period_data[period] = {}
                for metric_key in metric_keys:
                    period_data[period][metric_key] = []
                    period_data[period][f"forward_return_{metric_key}"] = []
            
            # Add valid data points for each metric
            for metric_key in metric_keys:
                metric_value = entry.get(metric_key)
                if (metric_value is not None and forward_return is not None and 
                    isinstance(metric_value, (int, float)) and isinstance(forward_return, (int, float))):
                    period_data[period][metric_key].append(float(metric_value))
                    period_data[period][f"forward_return_{metric_key}"].append(float(forward_return))
    
    return period_data

def calculate_correlations(metric_values: List[float], forward_return_values: List[float]) -> dict:
    """
    Calculate correlation statistics between a metric and forward return
    
    Args:
        metric_values: List of metric values (e.g., ROA or EBIT/PPE)
        forward_return_values: List of forward return values
        
    Returns:
        Dictionary with correlation statistics
    """
    
    if len(metric_values) < 2:
        return {
            "n_pairs": len(metric_values),
            "pearson_correlation": None,
            "pearson_pvalue": None,
            "ranked_correlation": None,
            "ranked_pvalue": None,
            "spearman_correlation": None,
            "spearman_pvalue": None,
            "error": "Insufficient data points for correlation"
        }
    
    # Convert to numpy arrays
    metric_array = np.array(metric_values)
    forward_return_array = np.array(forward_return_values)
    
    # Rank the data before correlating
    # Rankdata assigns ranks from 1 to n (where n = number of data points)
    # Average ranks are used for tied values
    metric_ranks = rankdata(metric_array, method='average')
    forward_return_ranks = rankdata(forward_return_array, method='average')
    
    # Calculate Pearson correlation on original values (linear relationship)
    pearson_corr, pearson_p = pearsonr(metric_array, forward_return_array)
    
    # Calculate correlation on ranked data (this is equivalent to Spearman)
    ranked_corr, ranked_p = pearsonr(metric_ranks, forward_return_ranks)
    
    # Also calculate Spearman for verification (should match ranked correlation)
    spearman_corr, spearman_p = spearmanr(metric_array, forward_return_array)
    
    # Calculate basic statistics
    metric_mean = np.mean(metric_array)
    metric_std = np.std(metric_array)
    forward_return_mean = np.mean(forward_return_array)
    forward_return_std = np.std(forward_return_array)
    
    return {
        "n_pairs": len(metric_values),
        "pearson_correlation": float(pearson_corr),
        "pearson_pvalue": float(pearson_p),
        "ranked_correlation": float(ranked_corr),
        "ranked_pvalue": float(ranked_p),
        "spearman_correlation": float(spearman_corr),
        "spearman_pvalue": float(spearman_p),
        "metric_mean": float(metric_mean),
        "metric_std": float(metric_std),
        "metric_min": float(np.min(metric_array)),
        "metric_max": float(np.max(metric_array)),
        "forward_return_mean": float(forward_return_mean),
        "forward_return_std": float(forward_return_std),
        "forward_return_min": float(np.min(forward_return_array)),
        "forward_return_max": float(np.max(forward_return_array))
    }

def print_statistics(stats: dict):
    """
    Print correlation statistics in a readable format
    
    Args:
        stats: Dictionary with correlation statistics
    """
    print("\n" + "="*80)
    print("ROA vs Forward Return Correlation Analysis")
    print("="*80)
    print(f"\nNumber of data points: {stats['n_pairs']:,}")
    print(f"\nROA Statistics:")
    print(f"  Mean: {stats['roa_mean']:.4f}")
    print(f"  Std Dev: {stats['roa_std']:.4f}")
    print(f"  Min: {stats['roa_min']:.4f}")
    print(f"  Max: {stats['roa_max']:.4f}")
    print(f"\nForward Return Statistics:")
    print(f"  Mean: {stats['forward_return_mean']:.2f}%")
    print(f"  Std Dev: {stats['forward_return_std']:.2f}%")
    print(f"  Min: {stats['forward_return_min']:.2f}%")
    print(f"  Max: {stats['forward_return_max']:.2f}%")
    print(f"\nCorrelation Results:")
    print(f"  Pearson Correlation (on original values): {stats['pearson_correlation']:.4f}")
    print(f"  Pearson p-value: {stats['pearson_pvalue']:.4e}")
    if stats['pearson_pvalue'] < 0.05:
        print(f"    -> Statistically significant (p < 0.05)")
    else:
        print(f"    -> Not statistically significant (p >= 0.05)")
    print(f"\n  Ranked Correlation (on ranked values): {stats['ranked_correlation']:.4f}")
    print(f"  Ranked p-value: {stats['ranked_pvalue']:.4e}")
    if stats['ranked_pvalue'] < 0.05:
        print(f"    -> Statistically significant (p < 0.05)")
    else:
        print(f"    -> Not statistically significant (p >= 0.05)")
    print(f"\n  Spearman Correlation (for verification): {stats['spearman_correlation']:.4f}")
    print(f"  Spearman p-value: {stats['spearman_pvalue']:.4e}")
    print(f"    -> Note: Ranked correlation should match Spearman correlation")
    print("\n" + "="*80)

def plot_ranks(roa_ranks: List[float], forward_return_ranks: List[float], 
               stats: dict, output_file: str = "roa_forward_return_ranks.png"):
    """
    Create a scatter plot of ranked ROA vs ranked forward return
    
    Args:
        roa_ranks: List of ROA ranks (1 to n)
        forward_return_ranks: List of forward return ranks (1 to n)
        stats: Dictionary with correlation statistics
        output_file: Output filename for the plot
    """
    plt.figure(figsize=(12, 8))
    
    # Create scatter plot
    plt.scatter(roa_ranks, forward_return_ranks, alpha=0.5, s=20)
    
    # Add labels and title
    plt.xlabel('ROA Rank (1 = lowest, ' + str(stats['n_pairs']) + ' = highest)', fontsize=12)
    plt.ylabel('Forward Return Rank (1 = lowest, ' + str(stats['n_pairs']) + ' = highest)', fontsize=12)
    plt.title('Ranked ROA vs Ranked Forward Return\n(All Stocks, All Periods)', fontsize=14, fontweight='bold')
    
    # Add correlation statistics as text
    stats_text = f"Ranked Correlation: {stats['ranked_correlation']:.4f}\n"
    stats_text += f"p-value: {stats['ranked_pvalue']:.4e}\n"
    stats_text += f"Number of data points: {stats['n_pairs']:,}\n"
    stats_text += f"Ranks range from 1 to {stats['n_pairs']}"
    
    plt.text(0.05, 0.95, stats_text, transform=plt.gca().transAxes,
             fontsize=10, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    # Add diagonal reference line (perfect correlation would follow this)
    max_rank = stats['n_pairs']
    plt.plot([1, max_rank], [1, max_rank], 'r--', alpha=0.3, label='Perfect Correlation')
    plt.legend()
    
    # Set equal aspect ratio and limits
    plt.xlim(0, max_rank + 50)
    plt.ylim(0, max_rank + 50)
    plt.gca().set_aspect('equal', adjustable='box')
    
    # Add grid
    plt.grid(True, alpha=0.3)
    
    # Tight layout
    plt.tight_layout()
    
    # Save plot
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\nPlot saved to {output_file}")
    
    # Show plot
    plt.show()

def detect_available_metrics(data: List[dict]) -> dict:
    """
    Detect which metrics are available in the data
    
    Args:
        data: List of stock data dictionaries
    
    Returns:
        Dictionary mapping metric keys to their display names and descriptions
    """
    available_metrics = {}
    metric_display_names = {
        'roa': 'ROA (Return on Assets)',
        'ebit_ppe': 'EBIT/PPE (EBIT per Property, Plant & Equipment)',
        'ebit_ppe_ttm': 'EBIT/PPE TTM (Trailing Twelve Months)'
    }
    
    # Check which metrics exist in the data by scanning all entries
    # Exclude non-metric keys
    excluded_keys = {'period', 'price', 'dividends', 'total_return', 'forward_return'}
    
    # First, find all potential metric keys by scanning all entries
    all_metric_keys = set()
    for stock in data:
        for entry in stock.get("data", []):
            for key, value in entry.items():
                if key not in excluded_keys:
                    # Check if it's a numeric value (could be a metric)
                    if value is not None and isinstance(value, (int, float)):
                        all_metric_keys.add(key)
    
    # Now check which of these have display names, or create default names
    for metric_key in sorted(all_metric_keys):
        if metric_key in metric_display_names:
            # Use the predefined display name
            available_metrics[metric_key] = metric_display_names[metric_key]
        else:
            # Create a default display name from the key
            # Convert snake_case to Title Case
            display_name = metric_key.replace('_', ' ').title()
            available_metrics[metric_key] = display_name
    
    return available_metrics

def get_metric_selection(available_metrics: dict) -> str:
    """
    Display a dynamic menu and get user's metric selection
    
    Args:
        available_metrics: Dictionary mapping metric keys to display names
    
    Returns:
        String indicating selected metric(s) or 'exit'
    """
    print("\n" + "="*80)
    print("Correlation Analysis - Metric Selection")
    print("="*80)
    print("\nSelect which metric to analyze:")
    
    # Build menu dynamically based on available metrics
    menu_items = []
    metric_keys = sorted(available_metrics.keys())  # Sort for consistent ordering
    
    # Add individual metrics
    for i, metric_key in enumerate(metric_keys, start=1):
        menu_items.append((str(i), metric_key, available_metrics[metric_key]))
        print(f"  {i}. {available_metrics[metric_key]}")
    
    # Add "All metrics" option if more than one metric
    if len(metric_keys) > 1:
        menu_items.append((str(len(metric_keys) + 1), 'all', 'All metrics'))
        print(f"  {len(metric_keys) + 1}. All metrics")
    
    # Add exit option
    exit_num = len(metric_keys) + (2 if len(metric_keys) > 1 else 1)
    menu_items.append((str(exit_num), 'exit', 'Exit'))
    print(f"  {exit_num}. Exit")
    
    print("="*80)
    
    max_choice = exit_num
    while True:
        try:
            choice = input(f"\nEnter your choice (1-{max_choice}): ").strip()
            
            # Find the menu item for this choice
            for num, key, _ in menu_items:
                if choice == num:
                    return key
            
            print(f"Invalid choice. Please enter a number between 1 and {max_choice}.")
        except KeyboardInterrupt:
            print("\n\nExiting...")
            return 'exit'
        except Exception as e:
            print(f"Error: {e}. Please try again.")

def print_correlations_over_time(results: List[dict], metric_name: str):
    """
    Print correlation for each period over time for a given metric
    
    Args:
        results: List of dictionaries with correlation results
        metric_name: Display name of the metric
    """
    print("\n" + "="*100)
    print(f"{metric_name} vs Forward Return Correlation by Period (Over Time)")
    print("="*100)
    print(f"\n{'Period':<15} {'Correlation':<15} {'p-value':<15} {'Significant':<15} {'N Pairs':<15}")
    print("-" * 100)
    
    # Sort results by period for chronological display
    sorted_results = sorted(results, key=lambda x: x.get('period', 0))
    
    for result in sorted_results:
        period = result.get('period', 'Unknown')
        ranked_corr = result.get('ranked_correlation')
        p_value = result.get('ranked_pvalue')
        n_pairs = result.get('n_pairs', 0)
        
        if ranked_corr is not None and p_value is not None:
            is_significant = p_value < 0.05
            significance = "Yes" if is_significant else "No"
            print(f"{str(period):<15} {ranked_corr:<15.4f} {p_value:<15.4e} {significance:<15} {n_pairs:<15}")
        else:
            print(f"{str(period):<15} {'N/A':<15} {'N/A':<15} {'N/A':<15} {n_pairs:<15}")
    
    print("="*100)

def print_roa_correlations_over_time(roa_results: List[dict]):
    """Print ROA correlation for each period over time (backward compatibility)"""
    print_correlations_over_time(roa_results, "ROA")

def print_ebit_ppe_correlations_over_time(ebit_ppe_results: List[dict]):
    """Print EBIT/PPE correlation for each period over time (backward compatibility)"""
    print_correlations_over_time(ebit_ppe_results, "EBIT/PPE")

def print_period_correlations_summary(results: List[dict], metric_name: str):
    """
    Print summary statistics for correlation results across all periods for a given metric
    
    Args:
        results: List of dictionaries with correlation results
        metric_name: Display name of the metric
    """
    if not results:
        return
    
    print("\n" + "="*100)
    print(f"{metric_name} vs Forward Return Correlation Summary")
    print("="*100)
    
    significant_count = 0
    correlations = []
    weights = []  # Number of data points for each period (for weighting)
    
    for result in results:
        ranked_corr = result.get('ranked_correlation')
        p_value = result.get('ranked_pvalue')
        is_significant = p_value < 0.05 if p_value is not None else False
        
        if is_significant:
            significant_count += 1
        if ranked_corr is not None:
            correlations.append(ranked_corr)
            weights.append(result.get('n_pairs', 0))  # Use number of data points as weight
    
    print("\nSummary Statistics Across All Periods:")
    print(f"  Total periods analyzed: {len(results)}")
    print(f"  Periods with significant correlation (p < 0.05): {significant_count}")
    if correlations:
        # Calculate weighted average correlation (weighted by number of data points)
        correlations_array = np.array(correlations)
        weights_array = np.array(weights)
        weighted_avg = np.average(correlations_array, weights=weights_array)
        
        print(f"  Average ranked correlation (unweighted): {np.mean(correlations):.4f}")
        print(f"  Weighted average ranked correlation (by data points): {weighted_avg:.4f}")
        print(f"  Median ranked correlation: {np.median(correlations):.4f}")
        print(f"  Min ranked correlation: {np.min(correlations):.4f}")
        print(f"  Max ranked correlation: {np.max(correlations):.4f}")
    print("="*100)

def print_period_correlations(roa_results: List[dict], ebit_ppe_results: List[dict]):
    """
    Print summary statistics for correlation results across all periods (backward compatibility)
    
    Args:
        roa_results: List of dictionaries with ROA correlation results
        ebit_ppe_results: List of dictionaries with EBIT/PPE correlation results
    """
    # Print ROA summary if results are provided
    if roa_results:
        print_period_correlations_summary(roa_results, "ROA")
    
    # Print EBIT/PPE summary if results are provided
    if ebit_ppe_results:
        print_period_correlations_summary(ebit_ppe_results, "EBIT/PPE")

def main():
    """
    Main function to calculate and display correlation analysis by period
    """
    # Load data first to detect available metrics
    print("Loading data from metrics.json...")
    data = load_data("metrics.json")
    
    if not data:
        print("No data loaded. Exiting.")
        return
    
    print(f"Loaded data for {len(data)} stock(s)")
    
    # Detect available metrics
    available_metrics = detect_available_metrics(data)
    
    if not available_metrics:
        print("No metrics found in data. Exiting.")
        return
    
    # Get user's metric selection
    selected_metrics = get_metric_selection(available_metrics)
    
    if selected_metrics == 'exit':
        print("Exiting program.")
        return
    
    # Determine which metrics to process
    if selected_metrics == 'all':
        metric_keys_to_process = list(available_metrics.keys())
    else:
        metric_keys_to_process = [selected_metrics]
    
    # Extract data grouped by period
    print(f"\nExtracting metrics and forward return data by period...")
    period_data = extract_data_by_period(data, metric_keys_to_process)
    
    print(f"Found {len(period_data)} unique periods")
    
    if len(period_data) == 0:
        print("No valid period data found. Exiting.")
        return
    
    # Calculate correlations for each period and each metric
    print("\nCalculating correlations for each period...")
    all_results = {metric_key: [] for metric_key in metric_keys_to_process}
    
    # Sort periods for consistent output
    sorted_periods = sorted([p for p in period_data.keys() if isinstance(p, str) or (isinstance(p, (int, float)) and p != 0)])
    
    for period in sorted_periods:
        for metric_key in metric_keys_to_process:
            metric_values = period_data[period].get(metric_key, [])
            forward_return_values = period_data[period].get(f"forward_return_{metric_key}", [])
            
            if len(metric_values) >= 2 and len(metric_values) == len(forward_return_values):
                stats = calculate_correlations(metric_values, forward_return_values)
                stats['period'] = period
                stats['metric_key'] = metric_key
                all_results[metric_key].append(stats)
    
    # Display results for each selected metric
    for metric_key in metric_keys_to_process:
        results = all_results[metric_key]
        if results:
            metric_name = available_metrics.get(metric_key, metric_key)
            print_correlations_over_time(results, metric_name)
    
    # Print summary statistics for each selected metric
    for metric_key in metric_keys_to_process:
        results = all_results[metric_key]
        if results:
            metric_name = available_metrics.get(metric_key, metric_key)
            print_period_correlations_summary(results, metric_name)

if __name__ == "__main__":
    main()

